[mypy]
python_version = 3.11
ignore_missing_imports = True
strict_optional = True

# Start small: only shared and data
[mypy-globomantics_shared.*]
disallow_untyped_defs = True

[mypy-globomantics_data.*]
disallow_untyped_defs = True
