[project]
name = "globomantics-monorepo"
version = "0.1.0"
description = ""
authors = [
    {name = "Ed Freitas",email = "64435900+ed-freitas@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests (>=2.32.5,<3.0.0)",
    "pandas (>=2.3.3,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ["py311"]
exclude = '''
(
    /build/
  | /dist/
  | /venv/
  | /.venv/
  | /env/
  | /\.git/
  | /.pytest_cache/
)
'''
