[build-system]
requires = ["flit-core>=3.2"]
build-backend = "flit_core.buildapi"

[project]
name = "globomantics_platform"
version = "0.1.0"
description = "Globomantics platform core"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Globomantics", email = "dev@globomantics.example" }
]

[tool.flit.module]
name = "globomantics_platform"
