[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "globomantics-cli"
version = "0.1.0"
dependencies = [
    "globomantics-shared",
    "globomantics-data",
    "globomantics-analytics",
    "globomantics-billing",
]
[project.scripts]
globomantics = "globomantics_cli.main:main"
